---

- hosts: database 
  become: yes
  
  tasks:
    - name: install tools
      apt: name={{item}} state=present update_cache=yes
      with_items:
        - python-mysqldb
  
    - name: install mysql-server
      apt: 
        name: mysql-server 
        state: present 
        update_cache: yes
      
    - lineinfile: 
        dest: /etc/mysql/my.cnf 
        regexp: ^bind-address 
        line: "bind-address = 0.0.0.0"
      notify: restart mysql
 
    - name: create visualapp database 
      mysql_db: 
        name: visualapp 
        state: present 

    - name: create visualapp user 
      mysql_user: 
        name: visualapp 
        password: visualapp 
        priv: visualapp.*:ALL 
        host: '%' 
        state: present

  handlers: 
    - name: restart mysql
      service: 
        name: mysql 
        state: restarted
