---

- hosts: webserver
  become: yes
  
  tasks:
    - name: install apache
      apt: 
        name: "{{ item }}" 
        state: present 
        update_cache: yes

      with_items:
       - apache2
       - libapache2-mod-wsgi
       - python-pip
       - python-virtualenv
       - python-mysqldb

    - name: start apache 
      service: 
        name: apache2 
        state: started 
        enabled: yes
  
    - name: enable mod_wsgi
      apache2_module: 
        state: present 
        name: wsgi
      notify: restart apache2

  handlers:
    - name: restart apache2
      service: 
        name: apache2 
        state: restarted
   
    - name: copy visualapp app source
      copy: 
        src: visualapp/app/ 
        dest: /var/www/visualapp 
        mode: 0755
      notify: restart apache

    - name: copy apache virtual host config
      copy: 
        src: visualapp/visualapp.conf 
        dest: /etc/apache2/sites-available 
        mode: 0755
      notify: restart apache

    - name: setup python vitualenv
      pip: 
        requirements: /var/www/visualapp/requirements.txt 
        virtualenv: /var/www/visualapp/.venv
      notify: restart apache

    - name: de-activate default apache site
      file: 
        path: /etc/apache2/sites-enabled/000-default.conf 
        state: absent
      notify: restart apache
     
    - name: activate visualapp apache site
      file: 
        src: /etc/apache2/sites-available/visualapp.conf 
        dest: /etc/apache2/sites-enabled/visualapp.conf 
        state: link
      notify: restart apache
